# See https://golangci-lint.run/usage/configuration/#config-file

run:
  timeout: 3m
  go: "1.21"

linters:
  enable:
    - errorlint
    - exhaustive
    - exportloopref
    - godox
    - goimports
    - misspell
    - nilerr
    - nolintlint
    - revive
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  nolintlint:
    require-specific: true
    require-explanation: true
  revive:
    #enable-all-rules: true
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: confusing-naming
      - name: get-return
      - name: modifies-parameter
      - name: confusing-results
      - name: modifies-value-receiver
      - name: atomic
      - name: empty-lines
      - name: duplicated-imports
      - name: identical-branches
      - name: defer
