# Configuration file for http://goreleaser.com
version: 2

builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - format: binary

dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/dailymotion-oss/{{.ProjectName}}:{{ .Version }}"
      - "ghcr.io/dailymotion-oss/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/dailymotion-oss/{{.ProjectName}}:v{{ .Major }}"
      - "ghcr.io/dailymotion-oss/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/dailymotion-oss/{{.ProjectName}}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

changelog:
  sort: asc
