style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/dailymotion-oss/octopilot
options:
  tag_filter_pattern: '^v'
  sort: "semver"
  commits:
    filters:
      Type:
        - build
        - chore
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - style
        - test
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      build: Build
      chore: Chore
      ci: CI
      docs: Documentation
      feat: New Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Style
      test: Tests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
  issues:
    prefix:
      - "#"
  refs:
    actions:
      - Closes
      - Fixes